included:
    - Sources

# rule identifiers to exclude from running
disabled_rules:
    - cyclomatic_complexity
    - large_tuple

shorthand_operator: warning
superfluous_disable_command: warning

# some rules are only opt-in
opt_in_rules:
    - empty_count

# configurable rules can be customized from this configuration file
line_length:
- 250
- 280
function_body_length:
- 55
- 80

file_length:
- 590
- 600
