platform :ios, '10.0'

target 'DemoTabbedApplication' do
  use_frameworks!

  pod 'QMobileDataStore', :path => '../../../QMobileDataStore'
  pod 'QMobileDataSync', :path => '../../../QMobileDataSync'
  pod 'QMobileAPI', :path => '../../../QMobileAPI'
  pod 'QMobileUI', :path => '../../'


  pod 'XCGLogger/UserInfoHelpers', :git => 'https://github.com/DaveWoodCom/XCGLogger.git', :tag => '5.0.5'

  pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON', :tag => '3.1.4'

  pod 'Kingfisher', '~> 3.0'
  pod 'IBAnimatable', '~> 4.0'
  pod 'Guitar', :git => 'https://github.com/ArtSabintsev/Guitar.git', :branch => 'swift3.2'
  pod 'ValueTransformerKit', :git => 'https://github.com/phimage/ValueTransformerKit', :tag => '0.0.1'
  pod 'BrightFutures', :git => 'https://github.com/Thomvis/BrightFutures', :tag => '5.2.0'
  
  pod 'SwiftMessages', :git => 'https://github.com/SwiftKickMobile/SwiftMessages', :tag => '3.5.1'

# for monitoring
  pod 'PinpointKit/ScreenshotDetector'

# in dev
  pod 'AZDialogView'
  pod 'LinearProgressBarMaterial'


# in debuging
pod 'NSLogger'
pod 'XCGLoggerNSLoggerConnector'

  #pod 'StyleKit', :git => 'https://github.com/146BC/StyleKit.git', :branch => 'develop'

end

post_install do |installer|
    puts "Updating all targets OTHER_SWIFT_FLAGS to add debug flag to Debug build config"
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if config.name == "Debug"
                config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['$(inherited)']
                if !config.build_settings['OTHER_SWIFT_FLAGS'].include? " \"-D\" \"DEBUG\""
                    config.build_settings['OTHER_SWIFT_FLAGS'] << " \"-D\" \"DEBUG\""
                end
            end
        end
    end
end
