platform :ios, '10.0'

target 'DemoTabbedApplication' do
  use_frameworks!

  pod 'QMobileDataStore', :path => '../../../QMobileDataStore'
  pod 'QMobileDataSync', :path => '../../../QMobileDataSync'
  pod 'QMobileAPI', :path => '../../../QMobileAPI'
  pod 'QMobileUI', :path => '../../'

  pod 'SwiftyJSON'
  pod 'StyleKit', :git => 'https://github.com/146BC/StyleKit.git', :branch => 'develop'

  pod 'Kingfisher'
  pod 'IBAnimatable'
  pod 'Guitar'
  pod 'ValueTransformerKit'
  pod 'RandomKit'
  pod 'BrightFutures'

  pod 'Watchdog'

end
