name: swift

on:
  push:
    paths:
      - "**/*.swift"
      - ".github/workflows/swift.yml"
  pull_request:
    paths:
      - "**/*.swift"
      - ".github/workflows/swift.yml"

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: swift build ios
      run: |
        sdk=`xcrun -sdk iphonesimulator -show-sdk-path`
        sdkVersion=`echo $sdk | sed -E 's/.*iPhoneSimulator(.*)\.sdk/\1/'`
        swift build  -Xswiftc "-sdk" -Xswiftc "$sdk" -Xswiftc "-target" -Xswiftc "x86_64-apple-ios$sdkVersion-simulator"
